### ISSUE TITLE
Wants an empty `github` file in order to generate.

### ISSUE THREAD

**Issue by illegalprime** [HackGT/hackgt-org-website#2]
I get this error:
```
Configuration file: /home/michael/cde/hackgt-org-website/_config.yml
Configuration file: /home/michael/cde/hackgt-org-website/_config.yml
github
jekyll 3.3.1 | Error:  No such file or directory @ rb_sysopen - github
```

When I do a `touch github` though it starts working. What is this file?

**Comment by jacobj10** [comment]
This is an error when parsing the CSV. It will work when I upload a dummy CSV in the right format (did not commit the CSV because it contains our info :+1: )

**Comment by jacobj10** [comment]
Added temp csv file with only my info
