### ISSUE TITLE
Event page adjustments

### ISSUE THREAD

**Issue by kexin-zhang** [HackGT/hackgt-org-website#49]
- Invert the colors into a dark theme for the top half. So, just make the background that dark navy color, and all the text white
- lots of white space between the animated arrow and the bottom of the page, can we make body text larger, and move the arrow so it sits closer to bottom of screen like Home page?

**Comment by mjkaufer** [comment]
I fixed exec positioning so it is more *responsive*, the word wrapping should be less of an issue now
