### ISSUE TITLE
Menu/navbar issues

### ISSUE THREAD

**Issue by kexin-zhang** [HackGT/hackgt-org-website#50]
- Contact is off center on mobile
![image](https://user-images.githubusercontent.com/17093911/35707565-347004ca-0778-11e8-97d5-60ad0ee49536.png)
- Make the big HackGT thing at the top smaller on mobile
- When you're on a page, that page link in the navbar should have the gradient thing on it.

**Comment by mjkaufer** [comment]
@jacobj10 do you know how to do the jekyll for the third bullet point (highlight the current page)?

You should be able to just add the `gradient-underline` class or something, I'm just not a LIQUID god
