### ISSUE TITLE
Mobile menu

### ISSUE THREAD

**Issue by kexin-zhang** [HackGT/hackgt-org-website#51]
Make a _real_ mobile menu

**Comment by mjkaufer** [comment]
😢

**Comment by mjkaufer** [comment]
ok so I kinda shrunk the text in the header on mobile so it looks less trash

**Comment by kexin-zhang** [comment]
yeah it looks better! can we also make the "HackGT" in the header smaller on mobile so it doesn't take up as much of the screen? also might be good to not have the gradient underline take up the whole width. see  #50 for a screenshot.

**Comment by mjkaufer** [comment]
cool, think I just fixed that

**Comment by joel99** [comment]
Addressed in #84
