### ISSUE TITLE
Attend and the arrow aren't visible on mobile home page unless you scroll

### ISSUE THREAD

**Issue by kexin-zhang** [HackGT/hackgt-org-website#52]

**Comment by mjkaufer** [comment]
@kexin-zhang @ehsanmasdar  I think I fixed this and it looks good on my devices, but can y'all check on your mobile devices too?

**Comment by kexin-zhang** [comment]
@mjkaufer yep, it's fixed on my device as well. we can close this issue whenever that PR gets merged.
