### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by kexin-zhang** [HackGT/hackgt-org-website#53]

**Comment by jacobj10** [comment]
Lol @kexin-zhang  is this something we have as an asset already or do we need to ping design team?

**Comment by kexin-zhang** [comment]
@jacobj10 Yeah, I kind of forgot about this lol, will reach out to design team again. Ty for the reminder!

**Comment by kexin-zhang** [comment]
Added in  c74f7ea247b000d6488215a4755580d149b81418
