### ISSUE TITLE
Exec positioning on mobile is off

### ISSUE THREAD

**Issue by kexin-zhang** [HackGT/hackgt-org-website#58]
On iOS:

![image uploaded from ios](https://user-images.githubusercontent.com/17093911/35836559-d81241fe-0aae-11e8-8ee0-003848ec489e.png)

**Comment by mjkaufer** [comment]
@kexin-zhang can you give me a specific device / dimensions? I'm playing around with mobile view in chrome devtools and I get some other weird formatting but nothing as bad as this on the virtual apple devices listed

**Comment by kexin-zhang** [comment]
@mjkaufer Turns out it's an iPhone 6 on iOS 10 (which isn't the newest iOS, that may be the issue). Definitely don't worry about it too much if we can't reproduce it on the latest version of iOS.
